# Generated by Django 5.2.7 on 2025-10-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='회사명')),
                ('homepage_url', models.URLField(blank=True, max_length=2083, null=True, verbose_name='홈페이지 URL')),
                ('recruits_url', models.URLField(blank=True, max_length=2083, null=True, verbose_name='채용 페이지 URL')),
                ('recruits_url_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='채용 URL 상태')),
                ('recruits_url_score', models.IntegerField(blank=True, null=True, verbose_name='채용 URL 신뢰도 점수')),
                ('logo_url', models.URLField(blank=True, max_length=2083, null=True, verbose_name='회사 로고 URL')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='산업 분야')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='회사 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사 목록',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='공고 제목')),
                ('post_url', models.URLField(max_length=2083, unique=True, verbose_name='공고 URL')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='주요 업무')),
                ('qualifications', models.TextField(blank=True, null=True, verbose_name='자격 요건')),
                ('preferred_qualifications', models.TextField(blank=True, null=True, verbose_name='우대 사항')),
                ('hiring_process', models.TextField(blank=True, null=True, verbose_name='채용 절차')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='혜택 및 복지')),
                ('hiring_message', models.TextField(blank=True, null=True, verbose_name='채용 메시지')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='근무지')),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='고용 형태')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='급여')),
                ('work_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='근무 시간')),
                ('posted_at', models.DateField(blank=True, null=True, verbose_name='게시일')),
                ('deadline_at', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('status', models.CharField(max_length=20, verbose_name='공고 상태')),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='수집일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='api.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '채용 공고',
                'verbose_name_plural': '채용 공고 목록',
                'db_table': 'job_postings',
            },
        ),
    ]
