# Generated by Django 5.2.7 on 2025-11-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='external_job_site',
            field=models.URLField(blank=True, help_text='If jobs are hosted on Saramin/JobKorea/Wanted etc.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hiring',
            field=models.BooleanField(default=False, help_text='Whether there appear to be active job postings (approx; refined later by job_collector).'),
        ),
        migrations.AddField(
            model_name='company',
            name='page_type',
            field=models.CharField(blank=True, choices=[('listing', 'Listing (board-style jobs page)'), ('one_page', 'One-page jobs section'), ('main', 'Main page has jobs'), ('external', 'External job site')], help_text='Type of careers page detected.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='post_type',
            field=models.CharField(blank=True, choices=[('text', 'Text-based postings'), ('image', 'Image-based postings'), ('external_link', 'Links to external job site')], help_text='How job postings are presented.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, help_text="Region inferred from site footer/address, e.g. 'Seoul', 'Busan'.", max_length=255, null=True),
        ),
    ]
