# Generated by Django 5.2.7 on 2025-11-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_external_job_site_company_hiring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='external_job_site',
            field=models.URLField(blank=True, help_text='외부채용사이트 주소', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='hiring',
            field=models.BooleanField(default=False, help_text='채용진행 여부'),
        ),
        migrations.AlterField(
            model_name='company',
            name='page_type',
            field=models.CharField(blank=True, choices=[('listing', 'Listing (board-style jobs page)'), ('one_page', 'One-page jobs section'), ('main', 'Main page has jobs'), ('external', 'External job site')], help_text='채용페이지 타입', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='post_type',
            field=models.CharField(blank=True, choices=[('text', 'Text-based postings'), ('image', 'Image-based postings'), ('external_link', 'Links to external job site')], help_text='채용포스트 분류', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, help_text='회사 지역', max_length=255, null=True),
        ),
    ]
