# Generated by Django 5.2.7 on 2025-11-18 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_external_job_site_alter_company_hiring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counseling_date', models.DateField(verbose_name='날짜')),
                ('student_code', models.CharField(max_length=50, verbose_name='학생ID')),
                ('name_alias', models.CharField(max_length=50, verbose_name='이름(가명)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여'), ('O', '기타')], max_length=1, verbose_name='성별')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='학력')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='전공')),
                ('academy_rank', models.IntegerField(blank=True, null=True, verbose_name='학원 성적(등수)')),
                ('career_summary', models.TextField(blank=True, verbose_name='경력')),
                ('career_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='경력기간(M)')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='과정명')),
                ('counseling_summary', models.TextField(blank=True, verbose_name='상담내용 요약')),
                ('counselor_name', models.CharField(blank=True, max_length=50, verbose_name='상담교사')),
                ('note', models.TextField(blank=True, verbose_name='비고(위험/특이사항)')),
                ('preferred_company_size', models.PositiveIntegerField(blank=True, help_text='학생이 희망하는 최소 근무 인원(예: 5, 10, 20, 50 등)', null=True, verbose_name='근무인원')),
                ('preferred_industry', models.CharField(blank=True, max_length=100, verbose_name='업종분류')),
                ('preferred_employment_type', models.CharField(blank=True, max_length=50, verbose_name='구인구분(신입,경력)')),
                ('preferred_job_skill', models.CharField(blank=True, max_length=255, verbose_name='구인기술')),
                ('preferred_location', models.CharField(blank=True, max_length=100, verbose_name='근무지')),
                ('preferred_salary', models.CharField(blank=True, max_length=100, verbose_name='급여')),
                ('tech_stack', models.CharField(blank=True, max_length=255, verbose_name='기술스택')),
                ('welfare_preferences', models.CharField(blank=True, help_text='식대, 재택근무, 건강검진, 교육비, 사내스터디, 컨퍼런스참가비, 운동비, 도서구입비, 경조사비, 경조휴가, 스톡옵션, 자율출퇴근제 중 선택', max_length=255, verbose_name='복리후생')),
                ('required_conditions', models.CharField(blank=True, help_text='사전에 정의된 조건 키만 콤마로 저장 (예: COMPANY_SIZE_10UP,BENEFIT_재택근무 등)', max_length=500, verbose_name='필수조건')),
            ],
            options={
                'verbose_name': '훈련생',
                'verbose_name_plural': '훈련생',
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='first_seen_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='최초수집일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성 공고'),
        ),
    ]
