# Generated by Django 5.2.7 on 2026-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trainee_jobposting_first_seen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='acc_mt',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='결산월(MM)'),
        ),
        migrations.AddField(
            model_name='company',
            name='bizr_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='사업자등록번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='대표자명'),
        ),
        migrations.AddField(
            model_name='company',
            name='dart_corp_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='DART 고유번호'),
        ),
        migrations.AddField(
            model_name='company',
            name='dart_modify_date',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DART 최종변경일(YYYYMMDD)'),
        ),
        migrations.AddField(
            model_name='company',
            name='est_dt',
            field=models.DateField(blank=True, null=True, verbose_name='설립일'),
        ),
        migrations.AddField(
            model_name='company',
            name='homepage_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='홈페이지 확인일시'),
        ),
        migrations.AddField(
            model_name='company',
            name='homepage_fail_count',
            field=models.IntegerField(default=0, verbose_name='홈페이지 연속 실패 횟수'),
        ),
        migrations.AddField(
            model_name='company',
            name='homepage_host',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='홈페이지 호스트'),
        ),
        migrations.AddField(
            model_name='company',
            name='homepage_last_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='홈페이지 마지막 HTTP 코드'),
        ),
        migrations.AddField(
            model_name='company',
            name='homepage_url_status',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='홈페이지 상태'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_norm',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='회사명 정규화 키'),
        ),
        migrations.AddField(
            model_name='company',
            name='source_meta',
            field=models.JSONField(blank=True, null=True, verbose_name='소스별 부가정보(JSON)'),
        ),
        migrations.AddField(
            model_name='company',
            name='stock_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, verbose_name='종목코드(상장)'),
        ),
        migrations.AddField(
            model_name='company',
            name='swdb_fin_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='SWDB 재무현황연도'),
        ),
    ]
